<?php

$sLangName = "Deutsch";
$aLang     = array(

    //Navigation
    'charset'                                                              => 'UTF-8',
    'd3points_TRANSL'                                                      => 'Bonuspunkte',
    'd3points_HELPLINK'                                                    => 'Bonuspunkte/',
    //ModCfg
    'd3mxd3points'                                                         => '<i class="fab fa-d3 d3fa-color-blue"></i> Bonuspunkte',
    'd3cfgd3points'                                                        => 'Konfiguration',
    'd3tbcld3points_settings_main'                                         => 'Konfiguration',
    'd3mxd3points_SETTINGS'                                                => 'Konfiguration',
    'd3mxd3points_SUPPORT'                                                 => 'Support',
    'D3_CFG_MOD_d3points_MODULEACTIVE'                                     => 'Modul aktiv',
    'D3_CFG_d3points_GENERAL_DEBUGACTIVE'                                  => 'Debug-Modus',
    'D3_CFG_d3points_TEST_MODUS'                                           => 'Test-Modus',
    'D3_CFG_MOD_d3points_ACTIVE'                                           => 'aktiv',
    'D3_CFG_MOD_d3points_INACTIVE'                                         => 'inaktiv',
    'D3_CFG_MOD_d3points_CRONJOBS_OWERVIEW'                                => 'CronJob / Funktionen',
    'D3_CFG_MOD_d3points_CRONJOBS_ACTIVE'                                  => 'Aktiv',
    'D3_CFG_MOD_d3points_LAST_STARTS_CRONJOBS'                             => 'letzte Ausführung:',
    'D3_CFG_MOD_d3points_CRONJOBS_LINK'                                    => 'Link',
    'D3_CFG_MOD_d3points_ACCESSKEY'                                        => 'Zugriffsschutz für den CronJob',
    'D3_CFG_MOD_d3points_CRONJOB_GENERALL'                                 => 'Cronjob',
    'D3_CFG_MOD_d3points_CRONJOB_NEWPOINTS'                                => 'Punktevergabe',
    'D3_CFG_MOD_d3points_VOUCHER_4_MAX_POINTS'                             => 'Automatische Gutscheinvergabe',
    'D3_CFG_MOD_d3points_SEND_FIRST_MAIL'                                  => 'E-Mail mit Bonuspunkte',
    'D3_CFG_MOD_d3points_SEND_REMINDER_MAIL'                               => 'Erinnerungs-E-Mails',
    'D3_CFG_MOD_d3points_CALCULATION'                                      => 'Berechnung der Bonuspunkte',
    'D3_CFG_MOD_d3points_FNC_CRONJOB_PRINT_STATUS'                         => 'CronJob: Ausgabe der Statusinformationen',
    'D3_CFG_MOD_d3points_FNC_CRONJOB_SEND_STATUS_TO'                       => 'CronJob: Ausgabe versenden an:',

    'D3_CFG_MOD_d3points_POINTS_SYSTEM'                                    => 'Punktesysteme',
    'D3_CFG_MOD_d3points_POINTS_SYSTEM_SCALE'                              => 'Staffelsystem (scalar)',
    'D3_CFG_MOD_d3points_POINTS_SYSTEM_LINEAR'                             => 'lineare Punktevergabe (linear)',
    'D3_CFG_MOD_d3points_POINTS_SYSTEM_SCALAR_SET'                         => 'Punkteverteilung für das Staffelsystem',
    'D3_CFG_MOD_d3points_POINTS_SYSTEM_LINEAR_SET'                         => 'Punkte für die lineare Punktevergabe',
    'D3_CFG_MOD_d3points_POINTS_SYSTEM_REVIEW_RATING_SET'                  => 'Punkte für Sternbewertung',
    'D3_CFG_MOD_d3points_POINTS_SYSTEM_REVIEW_TEXT_SET'                    => 'Punkte für Textbewertung',
    'D3_CFG_MOD_d3points_POINTS_SYSTEM_REVIEW_TEXT_MULTIPLE_REVIEWS'       => 'Mehrfach-Textbewertungen für Artikel',
    'D3_CFG_MOD_d3points_POINTS_SYSTEM_EE_MALL_ACCOUNT'                    => 'Shopübergreifendes Punktekonto (nur EE)',
    'D3_CFG_MOD_d3points_SELECT_ORDERS'                                    => 'Auswahlkriterien für die Punktevergabe an Bestellungen',
    'D3_CFG_MOD_d3points_SELECTION_DATE_LIMIT'                             => 'Zeitlimit für zurückliegende Bestellungen',
    'D3_CFG_MOD_d3points_SELECTION_DATE_RANGE'                             => 'Zeitspanne zwischen Bestellzeit und Punktevergabe',
    'D3_CFG_MOD_d3points_SELECTION_PRICE_LIMIT'                            => 'Minimalwert für den Warenbruttowert',
    'D3_CFG_MOD_d3points_DO_POINTS_FOR_USER_WITHOUT_ACCOUNT'               => 'Kunden ohne Kundenkonto erhalten Bonuspunkte',
    'D3_CFG_MOD_d3points_SELECTION_GROUPS_4_POINTS'                        => 'Kundengruppen freigeben',
    'D3_CFG_MOD_d3points_SELECTION_GROUPS_4_NO_POINTS'                     => 'Kundengruppen ausschlie&szlig;en',
    'D3_CFG_MOD_d3points_SELECTION_PAYMENT_DATE_PAYED_POINTS'              => 'Bezahldatum bei folgenden Bezahlarten prüfen',
    'D3_CFG_MOD_d3points_SELECTION_PAYMENT_4_NO_POINTS'                    => 'Keine Punkte bei folgenden Zahlarten',
    'D3_CFG_MOD_d3points_SELECTION_DELIVERYDATE_4_NO_POINTS'               => 'Versanddatum bei folgenden Bezahlarten prüfen',
    'D3_CFG_MOD_d3points_SELECTION_OXFOLDER_4_POINTS'                      => 'Bestellordner freigeben',
    'D3_CFG_MOD_d3points_SELECTION_OXFOLDER_4_NO_POINTS'                   => 'Bestellordner ausschlie&szlig;en',
    'D3_CFG_MOD_d3points_SELECTION_OXIP_INCL'                              => 'Notwendige Werte im Feld oxip',
    'D3_CFG_MOD_d3points_SELECTION_OXIP_EXCL'                              => 'Verbotene Werte im Feld oxip',
    'D3_CFG_MOD_d3points_SELECTION_OXTRANSSTATUS_INCL'                     => 'Notwendige Werte im Feld oxtransstatus',
    'D3_CFG_MOD_d3points_SELECTION_OXTRANSSTATUS_EXCL'                     => 'Verbotene Werte im Feld oxtransstatus',
    'D3_CFG_MOD_d3points_SELECTION_OXBILLEMAIL_INCL'                       => 'Erlaubte E-Mailadresse',
    'D3_CFG_MOD_d3points_SELECTION_OXBILLEMAIL_EXCL'                       => 'Verbotene E-Mailadresse',
    //Konfiguration ->Generierung Gutscheine
    'D3_CFG_MOD_d3points_VOUCHER'                                          => 'Generierung Gutscheine',
    'D3_CFG_MOD_d3points_VOUCHER_RATE_4_VOUCHER'                           => 'Bonuspunkte-Umrechnungskurs',
    'D3_CFG_MOD_d3points_POINTS_VOUCHER_OUT_PAYMENT'                       => 'Minimallimit für die Punkteumwandlung',
    'D3_CFG_MOD_d3points_POINTS_VOUCHER_AUTOMATIC_PAYOUT'                  => 'Automatische Gutscheinerstellung',
    'D3_CFG_MOD_d3points_POINTS_VOUCHER_NUMBER_OF_CHARAKTER'               => 'Anzahl der Stellen des Gutscheincodes',
    //Konfiguration -->Email
    'D3_CFG_MOD_d3points_EMAILS'                                           => 'Konfiguration E-Mails',
    'D3_CFG_MOD_d3points_EMAILS_BCC'                                       => 'Blindkopie-E-Mailadresse angeben',
    'D3_CFG_MOD_d3points_EMAILS_TEST'                                      => 'Test-E-Mailadresse angeben',
    'D3_CFG_MOD_d3points_SEND_FIRST_EMAIL'                                 => 'Zeitversatz zwischen Vergabe der Punkte und Benachrichtgung per E-Mail',
    //'D3_CFG_MOD_d3points_REMINDER'  				=> 'Einstellung Erinnerungsemails',
    'D3_CFG_MOD_d3points_REMINDER_DAYS_WAIT_4_FIRST_MAIL'                  => 'Zeitpunkt für versand der ersten E-Mail',
    'D3_CFG_MOD_d3points_REMINDER_DAYS_WAIT_4_NEXT_MAILS'                  => 'Intervall der Erinnerungs-E-Mail',
    'D3_CFG_MOD_d3points_REMINDER_AMOUNT_POINTS'                           => 'Mindestpunktestand Erinnerungs-E-Mail',
    'D3_CFG_MOD_d3points_MAIN_SAVE'                                        => 'Speichern',
    //Bezeichner
    'D3_CFG_MOD_d3points_LABEL_POINTS'                                     => 'Punkte',
    'D3_CFG_MOD_d3points_LABEL_DAYS'                                       => 'Tage',
    'D3_CFG_MOD_d3points_LABEL_MONTHS'                                     => 'Monate',
    'D3_CFG_MOD_d3points_LABEL_NO'                                         => 'Keine Angabe',
    'D3_CFG_MOD_d3points_LABEL_LETTER'                                     => 'Zeichen',
    //Spielwiese
    'd3tbcld3points_settings_demo'                                         => 'Beispielrechnung',
    'd3mxd3points_DEMO'                                                    => 'Beispielrechnung',
    'D3_CFG_MOD_d3points_DEMO_CALCULATE_POINTS'                            => 'Punkteberechnung',
    'D3_CFG_MOD_d3points_DEMO_CALCULATE_POINTS_PRICE_AMOUNT'               => 'Warenwert',
    'D3_CFG_MOD_d3points_DEMO_CALCULATE_POINTS_RATE'                       => 'Umrechnungsfaktor',
    'D3_CFG_MOD_d3points_DEMO_CALCULATE_POINTS_SCALAR'                     => 'Staffel',
    'D3_CFG_MOD_d3points_DEMO_CALCULATE_POINTS_SCALAR_POINTS'              => 'Punkte',
    'D3_CFG_MOD_d3points_DEMO_CALCULATE_POINTS_SCALAR_MIN'                 => 'von',
    'D3_CFG_MOD_d3points_DEMO_CALCULATE_POINTS_SCALAR_MAX'                 => 'bis',
    'D3_CFG_MOD_d3points_DEMO_CALCULATE_METHODE'                           => 'Rechenweg',
    'D3_CFG_MOD_d3points_DEMO_CALCULATE_POINTS_SUM'                        => 'Bonuspunkte',
    'D3_CFG_MOD_d3points_DEMO_CALCULATE_VOUCHER'                           => 'Gutscheinberechnung',
    'D3_CFG_MOD_d3points_DEMO_CALCULATE_VOUCHER_POINTS_SUM'                => 'Bonuspunkte',
    'D3_CFG_MOD_d3points_DEMO_CALCULATE_VOUCHER_AMOUNT'                    => 'Gutscheinwert',
    'D3_CFG_MOD_d3points_DEMO_CALCULATE_SUBMIT'                            => 'berechnen',
    //Wartung
    'd3tbcld3points_settings_maintenance'                                  => 'Wartung',
    'd3mxd3points_MAINTENANCE'                                             => 'Wartung',
    'D3_CFG_MOD_d3points_MAINTAINCE_RESET_ORDERS'                          => 'Alle Bestellungen zurücksetzen',
    'D3_CFG_MOD_d3points_MAINTAINCE_RESET_ORDERS_TXT'                      => 'Status neu setzten',
    'D3_CFG_MOD_d3points_MAINTAINCE_RESET_ORDERS_CONFIRM_UNSET'            => 'Bestellungen als unbearbeitet markieren',
    'D3_CFG_MOD_d3points_MAINTAINCE_RESET_ORDERS_CONFIRM_SET'              => 'Bestellungen als bearbeitet markieren',
    'D3_CFG_MOD_d3points_MAINTAINCE_RESET_ORDERS_CONFIRM'                  => 'Vorgang wirklich ausführen?',
    'D3_CFG_MOD_d3points_MAINTAINCE_RESET_ORDERS_CONFIRM_NOT'              => 'Fehlender Haken bei Bestätigung. Es wurde keine Aktion ausgeführt.',
    'D3_CFG_MOD_d3points_MAINTAINCE_RESET_SUCCESS'                         => 'Status wurde an %s Bestellungen gespeichert.',
    'D3_CFG_MOD_d3points_MAINTAINCE_RESET_ORDERS_NOT_STATUS'               => 'Kein Status ausgewählt.',
    'D3_CFG_MOD_d3points_MAINTAINCE_DELETE_ORDER'                          => 'Bonuspunkte einer einzelnen Bestellung löschen',
    'D3_CFG_MOD_d3points_MAINTAINCE_DELETE_ORDER_ORDERNR'                  => 'BestellNr',
    'D3_CFG_MOD_d3points_MAINTAINCE_RESET_ORDERS_TYP'                      => 'Aktion',
    'D3_CFG_MOD_d3points_MAINTAINCE_RESET_ORDERS_TYP_ERROR'                => 'Keine Aktion gewählt.',
    'D3_CFG_MOD_d3points_MAINTAINCE_RESET_ORDERS_TYP_DELETE'               => 'l&ouml;schen',
    'D3_CFG_MOD_d3points_MAINTAINCE_RESET_ORDERS_TYP_STORNO'               => 'stornieren',
    'D3_CFG_MOD_d3points_MAINTAINCE_RESET_ORDERS_COMMET'                   => 'Bemerkung',
    'D3_CFG_MOD_d3points_MAINTAINCE_RESET_ORDERS_SEND_MAIL'                => 'E-Mail versenden',
    'D3_CFG_MOD_d3points_MAINTAINCE_STORNO_POINTS_FROM_ORDER'              => 'Punkte von Bestellung %s storniert.',
    'D3_CFG_MOD_d3points_MAINTAINCE_DELETE_POINTS_FROM_ORDER'              => 'Punkte von Bestellung %s gelöscht.',
    'D3_CFG_MOD_d3points_MAINTAINCE_ORDER_DOES_NOT_EXIST'                  => 'Bestellung %s existiert nicht.',
    'D3_CFG_MOD_d3points_MAINTAINCE_STORNO_POINTS_FROM_ORDER_STILL_STONRO' => 'Bestellung %s wurde schon storniert.',
    'D3_CFG_MOD_d3points_MAINTAINCE_NO_POINTS_GIVEN'                       => 'Für Bestellung %s wurden noch keine Bonuspunkte vergeben.',
    'D3_CFG_MOD_d3points_MAINTAINCE_NO_OPTIONS_SELECTED'                   => 'Keine Option angegeben.',
    'D3_CFG_MOD_d3points_MAINTAINCE_NO_CHECKBOX_SET'                       => 'Aktion über die Checkbox nicht bestätigt.',
    'D3_CFG_MOD_d3points_MAINTAINCE_SAVE'                                  => 'speichern',
    //Bestellungen ->Stamm
    'ORDER_MAIN_D3POINTS_4_ORDER'                                          => '<b>Bonuspunkte</b> (D3)',
    'ORDER_MAIN_D3POINTS_4_ORDER_NOT_SET'                                  => 'keine Punkte vergeben',
    'ORDER_MAIN_D3POINTS_4_ORDER_STORNO'                                   => 'Stornierung',
    //Tab User
    'd3tbcluser_points'                                                    => '<img title="D³ Data Development" alt="D³" src="../modules/d3/modcfg/public/d3logo.php"> Bonuspunkte',
    'GENERAL_ADMIN_POINTS_USER'                                            => '<img title="D³ Data Development" alt="D³" src="../modules/d3/modcfg/public/d3logo.php"> Bonuspunkte',
    'D3_USER_POINTS_OVERVIEW'                                              => 'Bonuspunkte',
    'D3_USER_POINTS_HEAD_TYPE'                                             => 'Typ',
    'D3_USER_POINTS_HEAD_POINTS'                                           => 'Bonuspunkte',
    'D3_USER_POINTS_HEAD_DATE'                                             => 'Datum',
    'D3_USER_POINTS_HEAD_COMMENT'                                          => 'Kommentar',
    'D3_USER_POINTS_ORDERTYPE'                                             => 'Bestellung Nr.',
    'D3_USER_POINTS_POINTS_STORNO'                                         => '(storniert)',
    'D3_USER_POINTS_POINTS_STORNO2'                                        => 'storniert',
    'D3_USER_POINTS_VOUCHERTYPE'                                           => 'Gutschein Nr.',
    'D3_USER_POINTS_VOUCHER_REBOOK'                                        => 'Rückbuchung Gutschein',
    'D3_USER_POINTS_OTHERTYPE'                                             => 'manuell',
    'D3_USER_POINTS_TOTALSUM'                                              => 'Gesamtanzahl',
    'D3_USER_POINTS_NEWPOINTS'                                             => 'Neue Bonuspunkte manuell vergeben:',
    'D3_USER_POINTS_SETPOINTS'                                             => 'Punkte',
    'D3_USER_POINTS_DESCTEXT'                                              => 'Erklärungstext<br><small>Die Vergabe der Punkte kann der Kunde<br> in seinem Kundenkonto einsehen.</small>',
    'D3_USER_POINTS_REVIEWTYPE'                                            => 'Bewertung',
    'D3_USER_MSG_CREATED_NEW_POINTS'                                       => 'Punkte wurden gespeichert.',
    'D3_USER_MSG_POINTS_NOT_A_NUMBER'                                      => 'Kein gültiger Wert!<br>Keine Punkte vergeben.',
    'D3_USER_POINTS_SETPOINTS_SEND_EMAIL'                                  => 'E-Mail versenden',
    'D3_ACCOUNT_OPTIONS_MAIL_TXT_ADMIN'                                    => 'Der Kunde erhält folgende E-Mails:',
    'D3_ACCOUNT_OPTIONS_MAIL_FIRST_MAIL'                                   => 'Für eine Bestellung erhaltene Bonuspunkte',
    'D3_ACCOUNT_OPTIONS_MAIL_RATING_REVIEW'                                => 'Bonuspunkte für eine Artikelbewertung',
    'D3_ACCOUNT_OPTIONS_MAIL_REMINDER'                                     => 'Erinnerungs-E-Mail für vorhandene Bonuspunkte',
    'D3_ACCOUNT_OPTIONS_MAIL_VOUCHER'                                      => 'Erstellung eines Gutscheines',
    'D3_ACCOUNT_REMINDER_MAIL'                                             => 'Versand Erinnerungs-E-Mail',
    'D3_ACCOUNT_REMINDER_MAIL_LAST'                                        => 'letzte E-Mail',
    'D3_ACCOUNT_REMINDER_MAIL_NEXT'                                        => 'nächsten E-Mail (eventuell)',
    'D3_ACCOUNT_POINTS_VOUCHER_VALUE'                                      => 'Wert',
    'D3_ACCOUNT_POINTS_VOUCHER_RESERVED'                                   => 'Reserviert:',
    'D3_ACCOUNT_POINTS_VOUCHER_USED'                                       => 'Eingel&ouml;st am:',

    // Testmodus
    'D3_CFG_MOD_d3points_TESTMODUS_SETTING'         => 'Testmodus Einstellung',
    'D3_CFG_MOD_d3points_TESTMODUS_FOR_REVIEWS'     => 'Testmodus für Artikelbewertung',
    'D3_CFG_MOD_d3points_TESTMODUS_DISPLAY_ACCOUNT' => 'Kundenkonto im Testmodus anzeigen',
    'D3_CFG_MOD_d3points_TESTMODUS_FOR_GROUPS'      => 'Benutzergruppen für Testmodus',
    'D3_CFG_MOD_d3points_TESTMODUS_CREATE_VOUCHERS' => 'Erstellung von Gutscheinen im Testmodus',

    'D3_CFG_MOD_d3points_SETTINGS'                                         => 'Einstellungen',
    'D3_CFG_MOD_d3points_OPT_SETTINGS'                                     => 'Optionale Auswahlkriterien',
    'D3_CFG_MOD_d3points_LABEL_EUR_POINTS'                                 => '&euro;/Punkte',
    'D3POINTS_HELPLINK_CONFIG'                                             => 'Fragen-zu-speziellen-Modulen/Bonuspunkte/'
);