[{capture append="oxidBlock_content"}]
    [{assign var="template_title" value="D3_INC_ACCOUNT_HEADER_POINTS"|oxmultilangassign}]
    [{assign var="currency" value=$oView->getActCurrency()}]

    [{d3modcfgcheck modid="d3points"}][{/d3modcfgcheck}]
    [{if $mod_d3points}]
        [{block name="d3accountpoints_content"}]
            [{if $oModCfg_d3points->isThemeIdMappedTo('azure')}]
                [{include file="d3_account_points_azure.tpl"}]
            [{elseif $oModCfg_d3points->isThemeIdMappedTo('flow')}]
                [{include file="d3_account_points_flow.tpl"}]
            [{elseif $oModCfg_d3points->isThemeIdMappedTo('wave')}]
                [{include file="d3_account_points_wave.tpl"}]
            [{else}]
            [{/if}]
        [{/block}]
    [{/if}]
    [{insert name="oxid_tracker" title=$template_title}]
[{/capture}]

[{capture append="oxidBlock_sidebar"}]
    [{include file="page/account/inc/account_menu.tpl" active_link="d3pointsaccount"}]
[{/capture}]

[{include file="layout/page.tpl" sidebar="Left"}]
